[package]
name = "backend-rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-files = "0.4.1"
actix-http = "2.2.0"
actix-web-httpauth = "0.5.0"
actix-cors = "0.5.3"
actix-session = "0.4.0"

serde = "1.0.118"
serde_json = "1.0.61"

fake = "2.2"
rand = "0.7"

log = "0.4"
pretty_env_logger = "0.4.0"
